### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by VarIr** [kr-colab/ReLERNN#23]
The dependencies in requirements.txt and setup.py are identical, so it seems to me the instructions could be simplified to 
```
$ git clone https://github.com/kern-lab/ReLERNN.git
$ cd ReLERNN
$ pip install .
```
instead of 
```
$ git clone https://github.com/kern-lab/ReLERNN.git
$ cd ReLERNN
$ pip install -r requirements.txt
$ python setup.py install
```
Or is there any reason for the two steps and legacy install?

**Comment by jradrion** [comment]
Thank you for your suggestion, @VarIr!
