### ISSUE TITLE
memory allocate error on PREDICT

### ISSUE THREAD

**Issue by stsmall** [kr-colab/ReLERNN#25]
Hi,
I have successfully run SIMULATE and TRAIN, but am now running into a memory error on PREDICT:
"MemoryError: Unable to allocate 32.4 GiB for an array with shape (14212, 1801, 340) and data type float32"
I realize that this likely on my side of things, but I wanted to know if it was possible to pass a VCF to PREDICT that was a subset of the VCF used in the SIMULATE step? PREDICT seems to look for the VCF as an hdf5 ...
thanks,
@stsmall

**Comment by jradrion** [comment]
Hi again @stsmall,

OK, this is definitely due to an oversight on my part, where ReLERNN is trying to stuff the variants from an entire chromosome into memory without concern for memory. I'll implement a way to split up predictions and I will update this issue when I do.

Jeff

**Comment by stsmall** [comment]
Cool. Thanks!
I did get it around it on my side by using 4 GPUs :)
I was queued a while, but it is done now. 
thanks,
@stsmall

**Comment by jradrion** [comment]
@stsmall, good to hear! If you don't mind I'd like to keep this issue open as a to-do reminder, because ReLERNN should have an option to split predictions to avoid this issue in the future. Thank you for your feedback!

**Comment by stsmall** [comment]
No problem. Sorry if I closed the other one too soon. I appreciate your help and dedication to awesome software and easy to read paper.

**Comment by jradrion** [comment]
no worries, I'm just liable to forget about it without an open issue. Thanks!

**Comment by jradrion** [comment]
Hi @stsmall,

I added an option when running `ReLERNN_PREDICT` that should hopefully alleviate your `MemoryError` issues in the future. You can now set `--batchSizeOverride` to something < the number of prediction windows along a chromosome (14,212 in your example above). A lower value should use less memory but have a longer runtime than a higher value. I would say try setting `--batchSizeOverride` to maybe 500 or 1000 if you rerun predictions on these data in the future.
