### ISSUE TITLE
Question about software usage

### ISSUE THREAD

**Issue by taishudayo** [kr-colab/ReLERNN#33]
Hi
I would like to know if it is possible to use this software to estimate recombination rates and then analyze population demographics using linkage-disequilibrium-based Ne estimation that use recombination rates information.
If you have time, please tell me.

**Comment by andrewkern** [comment]
Hi @taishudayo -- that sounds a bit circular to me? i.e. the recombination rates will be inferred from LD, so if you use them later LD isn't in some sense a degree of freedom.

**Comment by yangfangyuan0102** [comment]
Hi, @andrewkern 
Here is another question. Are there any suggested values for parameters such as --nTrain,--nVali,--nEpochs,--nValSteps, etc. Although I know it seems like bigger is better, it's completely unclear for me how to set them. For example, --nEpochs and --nValSteps were set to 2 in the example, how much is recommended for real data to get a not bad result? 20, 2000 or 200000? Many thanks.
