### ISSUE TITLE
Is there a method to convert the result to other window size based results

### ISSUE THREAD

**Issue by jiangzy26** [kr-colab/ReLERNN#34]
Hi,
    I got the predicted result from using ReLERNN, and Now I want to convert the result to other window size, like 50kb, and convert to map file used for the input of Relate (https://myersgroup.github.io/relate/input_data.html#Prepare), could you share some methods to do such work?

Thanks.

**Comment by andrewkern** [comment]
Hi there. Essentially you will want to smooth your results to some new window size. We don't have official methods for this but you don't need anything special I think? Simply using numpy tools or similar should get you there, if I understand correctly what you are hoping to do
