### ISSUE TITLE
ReLERNN_PREDICT_HOTSPO unable to run

### ISSUE THREAD

**Issue by Joyce121** [kr-colab/ReLERNN#35]
When I run ReLERNN_PREDICT_HOTSPOT with default parameters, I get an error of

File "/project-whj/software/ReLERNN/ReLERNN/ReLERNN_PREDICT_HOTSPOT", line 100, in main
    pred_sequence = VCFBatchGenerator(**bds_pred_params)
TypeError: __init__() got an unexpected keyword argument 'WIN'

Even using the examples file of the software, I don't know how to solve it, please give me your guidance

**Comment by jradrion** [comment]
Hi @Joyce121, unfortunately the hotspot prediction code was exploratory/experimental and is not currently being developed. The working functions of ReLERNN are those that are described in the README. I apologize for the confusion. I will discuss removing the hotspot prediction code from the repo to avoid further confusion. Thank you for bringing this to my attention.
