### ISSUE TITLE
what is the recommended threshold for maf filtering

### ISSUE THREAD

**Issue by Joyce121** [kr-colab/ReLERNN#38]
When I run ReLERNN with different MAF parameters, I get the exact opposite pattern of three populations.  How do I solve this problem, what is the recommended threshold for maf filtering?

**Comment by andrewkern** [comment]
This doesn't sound like a problem as much as a feature of your data. What MAF cutoff are you using? What is your sample size?

**Comment by Joyce121** [comment]
&nbsp;Filtering the maf=0.1,geno=0.2 for all populations together, as opposed to filtering the maf=0.1,geno=0.2 for different populations separately, results in the opposite pattern of three&nbsp;populations (wild, eary-domastiicated,improved),&nbsp;


20 samples for 6 breeds and 10 samples for 2 breeds

Can you give some guidance as to whether I should remove variants with low minor allele frequencies separately for different populations?
&nbsp;


Joyce
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andrew ***@***.***&gt;; 
发送时间: 2023年5月15日(星期一) 晚上10:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kr-colab/ReLERNN] what is the recommended threshold for maf filtering (Issue #38)






这听起来不像是一个问题，而像是数据的一个特性。你用的是什么MAF截止阀？你的样本容量是多少？

—
直接回复此邮件，在GitHub上查看，或者取消订阅.
您收到此消息是因为您创作了该线程。消息ID:<kr-colab/Re le ***@***.***与&gt;.

**Comment by andrewkern** [comment]
Sorry I don't follow-- what is `geno=0.2`? 

Given that you are using the `--maf` flag these are pooled samples?

Generally-- yes you should remove low frequency variants from each separate population
