### ISSUE TITLE
How many diploid samples should be at least used

### ISSUE THREAD

**Issue by jiangzy26** [kr-colab/ReLERNN#40]
Hi, I am wondering how many diploid samples should be used, I found the paper used at least 4 chromosomes, so, for diploid samples, at least two samples should be used. Am I right? And what about the accuracy? 
Thank you very much

**Comment by andrewkern** [comment]
more samples will give you greater accuracy, but yes N=4 chromosomes is the minimum we have experimented with

**Comment by jiangzy26** [comment]
Thank you, I downloaded re-sequencing data from NCBI, only two diploid samples are the same species, so, I am trying to use these two samples to calculate the recombination rate, I'll give it a try, thank you for your answer.
