### ISSUE TITLE
Issue with chromosome length

### ISSUE THREAD

**Issue by jbruxaux** [kr-colab/ReLERNN#44]
Hi!

I am facing a very usual issue with ReLERNN regarding chromosome length. I am studying a species with chromosomes longer than 2,147,483,647 bp which is the usual limit for integer storage in memory.
I can of course divide my chromosomes to take that into account (which I usually have to do, as most software have the same issue), but if you could consider that for one of your next releases, it would be amazing!

Thanks a lot!

**Comment by andrewkern** [comment]
thanks. i think the thing to do here is definitely to break the chromosome into chunks for processing.
