### ISSUE TITLE
very different corrections when bootstrapping

### ISSUE THREAD

**Issue by jbruxaux** [kr-colab/ReLERNN#45]
Hi!

I used ReLERNN to estimate the recombination rate along a very long genome, and ran the analyses by pieces of 500Mb. The results between the different parts are comparable when I use the results of the "predict" function, but differ a lot after correction with the "bscorrect" function.
For example, before correction:
![recombination_rate_1Mb_chr8_2](https://github.com/kr-colab/ReLERNN/assets/56797476/911bf4d0-a21b-426c-93ba-d9ce4c35e9cd)
And after correction:
![recombination_rate_1Mb_chr8](https://github.com/kr-colab/ReLERNN/assets/56797476/c9c7a869-e906-49c4-8302-499301f0aac3)
Any idea what could cause such differences? Is there anything I should do?
Thanks in advance!

**Comment by andrewkern** [comment]
interesting behavior here. is there any reason to believe that that portion of the chromosome is non-recombining?

**Comment by jbruxaux** [comment]
No, not at all. Each portion is 500Mb long (except the last one that is shorter) and harbor a lot of SNPs, and there is nothing different on any other parameter for that region (heterozygosity, nucleotide diversity...).

**Comment by andrewkern** [comment]
can you rerun the BSCORRECT module? I wonder if you will get a different answer?

**Comment by jbruxaux** [comment]
I will have to wait for a few days (GPU nodes in maintenance on our cluster), but I will try as soon as possible.

**Comment by andrewkern** [comment]
you might also try this on a cpu?

**Comment by jbruxaux** [comment]
Hi!

Sorry, it took me a few weeks to come back to this, but I re-ran the analysis on a smaller chromosome (only the BSCORRECT part), and I get the exact same result as last time (using the cmp command). So this part is at least consistent.

**Comment by andrewkern** [comment]
okay! this is very strange. any chance this has to do with seeds being maintained across runs? are you setting seeds manually?

**Comment by jbruxaux** [comment]
Yes, I used the same seed!
I re-ran again with different seeds, and here is what I get (for a smaller chromosome).
The original run:
![recombination_rate_1Mb_chr12_3](https://github.com/kr-colab/ReLERNN/assets/56797476/6f2cfc04-b96d-496d-a14b-ead39e813a9a)
The new run:
![recombination_rate_1Mb_chr12_4](https://github.com/kr-colab/ReLERNN/assets/56797476/8d88e4a9-1e1e-451a-8baf-745bff68b224)
For reference, the uncorrected results:
![recombination_rate_1Mb_chr12_2](https://github.com/kr-colab/ReLERNN/assets/56797476/f489af87-6b9d-4540-b695-354b8ed1c319)

**Comment by andrewkern** [comment]
okay this is definitely a seed issue. when is the last time you pulled the code? we recently fixed a potential bug in commit #48 which may affect bootstrapping with a manual seed.

**Comment by nspope** [comment]
what version are you using @jbruxaux ?  there was a bug fixed wrt to setting seeds a couple months ago ([here](https://github.com/kr-colab/ReLERNN/pull/48#issue-2165534877)) but you'll have to use the current github version of the repo

**Comment by andrewkern** [comment]
> what version are you using @jbruxaux ? there was a bug fixed wrt to setting seeds a couple months ago ([here](https://github.com/kr-colab/ReLERNN/pull/48#issue-2165534877)) but you'll have to use the current github version of the repo

jinx

**Comment by jbruxaux** [comment]
A quick update. I re-ran the analysis from scratch without any seed (and with the last ReLERNN version). I still see this pattern, but not as strongly.
Here are the non-corrected results:
![recombination_rate_1Mb_chr12_6](https://github.com/kr-colab/ReLERNN/assets/56797476/d03f5776-a3b0-455e-8a0f-ad77055110d2)

And here are the corrected results:
![recombination_rate_1Mb_chr12_5](https://github.com/kr-colab/ReLERNN/assets/56797476/d3041889-7bd7-4c50-8c67-e5619879a68a)

What do you think?

**Comment by nspope** [comment]
Hey @jbruxaux sorry for the long silence ... if you still have your script handy, could you please post the exact invocation for BSCORRECT? Were you using the default arguments; or a copy-paste from the `examples/example_pipeline.sh` (e.g. with `--nSlice 2 --nReps 2`); or something else? Thanks!

**Comment by jbruxaux** [comment]
I indeed used the example_pipeline.sh script, with --nSlice 2 --nReps 2. So that explains the issue. I will give it another try with more reasonable values. Thank you for your feedback!

**Comment by andrewkern** [comment]
great to hear
