### ISSUE TITLE
ReLERNN_SIMULATE not splitting vcf file properly

### ISSUE THREAD

**Issue by menietoblazquez** [kr-colab/ReLERNN#47]
Dear users,

I have used ReLERNN with a previous individuals resequencing data with no problem at all.

However, I am running into problems with a new dataset. It seems ReLERNN fails in the step of splitting the vcf into the different chromosome vcfs. By looking at this directory for the analzsis that previously worked, I see there are files missing. 

[s_menb@jupiter SS1]$ cd splitVCFs/
[s_menb@jupiter splitVCFs]$ ll
total 4204
-rw-r--r--. 1 s_menb clusteruser 1285117 Mar  1 10:59 SS1.m2M2.recode.CLEAN_Chr1:0-61357614.hdf5
-rw-r--r--. 1 s_menb clusteruser 1284380 Mar  1 10:59 SS1.m2M2.recode.CLEAN_Chr2:0-58906861.hdf5
-rw-r--r--. 1 s_menb clusteruser 1162613 Mar  1 10:59 SS1.m2M2.recode.CLEAN_Chr3:0-53163979.hdf5
-rw-r--r--. 1 s_menb clusteruser  566572 Mar  1 10:59 SS1.m2M2.recode.CLEAN_Chr4:0-17018963.hdf5

My vcf file (for a single individual was created using Platypus and filtering for biallelic positions.

My bed file is tab separated as follows:

Chr1    0       61357614
Chr2    0       58906861
Chr3    0       53163979
Chr4    0       17018963

And below the error message:

Traceback (most recent call last):
  File "/cluster/software/relernn/ReLERNN-1.0.0_ve/bin/ReLERNN_SIMULATE", line 245, in <module>
    main()
  File "/cluster/software/relernn/ReLERNN-1.0.0_ve/bin/ReLERNN_SIMULATE", line 160, in main
    thetaW=maxS/a
ZeroDivisionError: division by zero

Any ideas or suggestions?

Best wishes

ME

**Comment by menietoblazquez** [comment]
This problem solved once I used a vcf file with more than one individual.

**Comment by andrewkern** [comment]
yes you need more than one sample to run this software
