### ISSUE TITLE
NumPy Version Related Error

### ISSUE THREAD

**Issue by mbursell** [kr-colab/ReLERNN#50]
Hi! I am trying to get the example for ReLERNN working but I keep getting a NumPy version error where it wants a newer version of NumPy. Do you know which line in which script specifies the version of NumPy?

**Comment by andrewkern** [comment]
what versions are you working with? please post the output from `pip list`

**Comment by mbursell** [comment]
Hi! I apologize, I forgot to remove this once we got things working. We got
it to work with the versions specified on GitHub. I think we were having
some interference from some programs previously installed with conda.

Thanks,

Maddy Bursell

**Comment by andrewkern** [comment]
sounds good- thanks for letting me know!
