### ISSUE TITLE
Wrong auto-estimate of #CPUs (Slurm)

### ISSUE THREAD

**Issue by VaiaPatta1985** [kr-colab/ReLERNN#55]
The automatic estimate of the number of CPUs available is wrong on an HPC cluster with Slurm scheduler. The program counts all CPUs on the node, not just the ones allocated by Slurm. As a result, if it has not been allocated the whole node, it tries to start too many processes and it crashes.

To fix this, it should detect whether the environment variable `SLURM_NTASKS` has been set, and if so, set the number of processes equal to: either `SLURM_NTASKS * SLURM_CPUS_PER_TASK` (if `SLURM_CPUS_PER_TASK` has been set), or `SLURM_NTASKS` (if `SLURM_CPUS_PER_TASK` has not been set). If `SLURM_NTASKS` is unset, proceed as before.

The problem is of course resolved by using the `-t` flag. It is, however, inconvenient that one must then also alter the `example_pipeline.sh` and `example_pipeline_pool.sh` scripts, which are meant as elementary ready-to-run tests.

**Comment by andrewkern** [comment]
this isn't an issue with ReLERNN but instead a feature of how tensorflow and SLURM operate together. If you wish to run using a SLURM cluster, yes you need to control the number of CPUs

**Comment by VaiaPatta1985** [comment]
Alright, but can the example pipelines (which are run without command line parameters) be amended accordingly? I can easily make that change myself if you agree.
