### ISSUE TITLE
Error: chromosomes have different sample sizes!

### ISSUE THREAD

**Issue by mbursell** [kr-colab/ReLERNN#56]
Hi! I am running ReLERNN on two populations of sheep (each with 10 samples) and chromosomes 1-26. I got this error for both populations. My initial thoughts were that some of my filtering may have left some samples with a 0 snp count for certain chromosomes but when I printed out the snp count per sample per chromosome, all had many snps (well into thousands). I followed a previous resolved issue and checked if windowSizes.txt was empty and it was.  Do you know what is happening or what I should try? I attached part of my vcf and my ReLERNN script for one population. As background, I have run the example and other species successfully. 

[first_6000_IR_sheep_autosomes_biallelic_fixup.vcf.gz](https://github.com/user-attachments/files/15565414/first_6000_IR_sheep_autosomes_biallelic_fixup.vcf.gz)

[IR.txt](https://github.com/user-attachments/files/15566121/IR.txt)

**Comment by andrewkern** [comment]
I'm guessing this is simple formatting error-- what happens if you run the chromosomes separately? i.e., as different VCF inputs?

**Comment by mbursell** [comment]
Hi! I went back and ran it with chromosome 1 and it worked fine. I then looked more closely at the full vcf and realized that there were some issues with the path to the file and it is now running. Sorry! Thank you for the quick response.
